name: extendedip
description: Extended functionality for an InternetAddress.
version: 1.0.0
repository: https://github.com/fischerscode/dart-extendedIP
issue_tracker: https://github.com/fischerscode/dart-extendedIP/issues
documentation: https://pub.dev/documentation/extendedip/latest/

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
